apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloperiodic
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helloperiodic           
            image: "r.cfcr.io/raducrisan/periodicapp"
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: NETCORE_ENVIRONMENT
              value: "Development"
            - name: "connatix__environment"
              value: "Development"
          imagePullSecrets:
          - name: cfcrioregcred
          restartPolicy: OnFailure
          dnsPolicy: ClusterFirst
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
---